spring:
  datasource:
    username: postgres
    password: zoe_api
    url: jdbc:postgresql://localhost:5432/zoe
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mail:
    host: smtp.gmail.com
    port: 587
    username: zoeprodutos@gmail.com
    password: qpgutbawqkkevtgk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    unprotected-endpoints: /v3/api-docs/**, /swagger-ui/**, /actuator/**, /api/exception
  springdoc:
    version: 2.0.0
